cashback/urls.py
from django.urls import path
from . import views

app_name = 'cashback'

urlpatterns = [
    #views
    path('', views.view_login, name='view_login'),
    path('view_register', views.view_register, name='view_register'),
    path('view_user', views.view_user, name='view_user'),
    path('view_admin', views.view_admin, name='view_admin'),
    #functionalities
    path('create_user', views.create_user, name='create_user'),
    path('login_user', views.login_user, name='login_user'),
    path('logout_user', views.logout_user, name='logout_user'),
    path('add_to_budget', views.add_to_budget, name='add_to_budget'),
    path('remove_from_budget', views.remove_from_budget, name='remove_from_budget'),
]

cashback_app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cashback.urls'))
]

cashback/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
import datetime

# Create your models here.
class User(models.Model):
    category = models.CharField(max_length=5, default='user')
    username = models.CharField(max_length=30, default='username')
    password = models.CharField(max_length=30, default='password')
    budget   = models.FloatField(default=0.0, validators=[MinValueValidator(0.0), MaxValueValidator(1000000)])
    user_hash = models.CharField(max_length=5, default='*****')

    def __str__(self):
        return "{}, {}, {}".format(self.username, self.user_hash, self.budget)

class Logs(models.Model):
    user_hash = models.CharField(max_length=5, default='*****')
    amount   = models.CharField(max_length=1000, default='0')
    date_time = models.CharField(max_length=10, default=datetime.datetime.today())

cashback/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse
from . import models
import json
import datetime

# Create your views here.
def view_login(request):
    return render(request, 'login.html', context={})

def view_register(request):
    return render(request, 'register.html', context={})

def view_user(request):
    return render(request, 'user.html', context={})

def view_admin(request):
    return render(request, 'admin.html', context={})

#functionalities
def create_user(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    try:
        user = models.User.objects.get(username=username)
        return render(request, 'register.html', context={'msg':'username already taken.'})
    except models.User.DoesNotExist:
        user = models.User(username=username, password=password, category='user')
        user.save()
        user_hash = hash(str(user.id))
        user.user_hash = user_hash
        user.save()
        return render(request, 'login.html', context={'msg':'user created succesfully!'})

#
def login_user(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    try:
        user = models.User.objects.get(username=username, password=password)
        user.state = 1
        user_hash = user.user_hash
        logs = models.Logs.objects.filter(user_hash = user_hash)
        if(user.category == 'admin' and user.state == 1):
            return render(request, 'admin.html', context={'user':user, 'budget': round(user.budget)})
        elif(user.category == 'user' and user.state == 1):
            return render(request, 'user.html', context={'user':user, 'logs':logs, 'amount': round(user.budget, 2)})
        else:
            return render(request, 'login.html', context={})
    except models.User.DoesNotExist:
        return render(request, 'login.html', context={'msg':'username or password incorrect.'})
#
def logout_user(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    try:
        user = models.User.objects.get(username=username, password=password)
        user.state = 0
        return render(request, 'login.html', context={})
    except models.User.DoesNotExist:
        return render(request, 'login.html', context={})

#

def add_to_budget(request):
    body = json.loads(request.body)
    amount = body['amount']
    user_hash = body['user_hash']
    if(user_hash == ''):
        return HttpResponse(404)
    try:
        target = models.User.objects.get(user_hash = user_hash)
        #add 0.09%
        target.budget += round(float(amount) * 0.09, 2)
        log = models.Logs(user_hash=user_hash, amount='+{}'.format(round(float(amount) * 0.09, 2)), date_time=datetime.date.today())
        target.save()
        log.save()
        return HttpResponse(200)
    except models.User.DoesNotExist:
        return HttpResponse(404)

def remove_from_budget(request):
    body = json.loads(request.body)
    amount = body['amount']
    user_hash = body['user_hash']
    print(body)
    if(user_hash == ''):
        print('hi')
        return HttpResponse(404)
    try:
        target = models.User.objects.get(user_hash = user_hash)
        log = models.Logs(user_hash=user_hash, amount='-{}'.format(amount, date_time=datetime.date.today()))
        #add 0.09%
        target.budget -= round(float(amount), 2)
        if(target.budget >= 0):
            target.save()
            log.save()
            return HttpResponse(200)
        else:
            return HttpResponse(404)
    except models.User.DoesNotExist:
        return HttpResponse(404)

cashback/templates/admin.html
{% load static %}
<html>
	<head>
		<title>Admin</title>
		<link rel='stylesheet' href='{% static "admin.css" %}' />
	</head>
	<body>
		<form style="display:inline-block" method="post" action="{% url "cashback:logout_user" %}">
			{% csrf_token %}
			<input type="hidden" name="username" value="{{user.username}}" />
			<input type="hidden" name="password" value="{{user.password}}" />
			<button>Salir</button>
		</form>
		<div id='div-container'>
			<form method='post' action='#' id="cashback-form">
				{% csrf_token %}
				<h1>Cash back!</h1>
				<h3>Agregar o remover monto</h3>	
				<label>Usuario: {{user.username}}</label><br>

				<video id="scanner-frame"></video>
				<div id="scanner-overlay"></div>
				<p id="scanner-message"></p>

				<label>Monto:</label>
				<input type="hidden" id="user_hash" name="user_hash" value="" />
				<input type='number' id='inp-monto' name="amount" />
				<button id="add-btn">Agregar</button>
				<button id="remove-btn">Remover</button>
			</form>	

		</div>
		<script src="{% static 'admin_qr.js' %}" type="module"></script>
		<script>
		</script>
	</body>
</html>

cashback/templates/login.html
{% load static %}
<html>
	<head>
		<title>Login</title>
		<link rel='stylesheet' href='{% static "login.css" %}' />
	</head>
	<body>
		<div id='div-container'>
			<form method='post' action='{% url "cashback:login_user" %}'>
				{% csrf_token %}
				<h3>Negocio de las frutas!</h3>	
				<label>Usuario:</label>
				<input type='text' id='inp-username' name='username'/>
				<label>Contraseña:</label>
				<input type='password' id='inp-password' name='password'/>
				<button>Ingresar</button>
				<p>¿No tienes cuenta? haz click <a href='{% url "cashback:view_register" %}'>aquí</a> para crearte una!</p>
				<br><p>{{msg}}<p>
			</form>	
		</div>
	</body>
</html>

cashback/templates/register.html
{% load static %}
<html>
	<head>
		<title>Register</title>
		<link rel='stylesheet' href='{% static "login.css" %}' />
	</head>
	<body>
		<div id='div-container'>
			<form method='post' action='{% url "cashback:create_user" %}'>
				{% csrf_token %}
				<h3>Negocio de las frutas!</h3>	
				<label>Usuario:</label>
				<input type='text' id='inp-username' name="username" />
				<label>Contraseña:</label>
				<input type='password' id='inp-password' name="password" />
				<button>Ingresar</button>
				<p>¿No tienes cuenta? haz click <a href='{% url "cashback:view_login" %}'>aquí</a> para crearte una!</p>
				<br><p>{{msg}}</p>
			</form>	
		</div>
	</body>
</html>

cashback/templates/user.html
{% load static %}
<html>
	<head>
		<title>Login</title>
		<link rel='stylesheet' href='{% static "user.css" %}' />
	</head>
	<body>
		<!--user data-->
		<input type="hidden" id="user_hash" value="{{user.user_hash}}" />
		<form method="post" action="{% url "cashback:logout_user" %}">
			{% csrf_token %}
			<input type="hidden" name="username" value="{{user.username}}" />
			<input type="hidden" name="password" value="{{user.password}}" />
			<button>Salir</button>
		</form>
		<div id='div-container'>
			<h2>User: {{user.username}}</h2>
			<img alt='QR' id='qr_img' />
			<div id='div-details'>
				<h3>Saldo: {{amount}}$</h3>
				<h3>Últimos trámites:</h3>
				<div id='div-last-purchases'>
					{% for el in logs %}
						<div class='div-purchase'>
							<p class='p-purchase-date-time'>{{el.date_time}}</p>
							<p class='p-purchase-amount'>{{el.amount}}</p>
						</div>
					{% endfor %}
				</div>
			</div>
		</div>
		<script src="{% static "qr_show.js" %}"></script>
	</body>
</html>